### ISSUE TITLE
any chance you could compile to run on OSX?

### ISSUE THREAD

**Issue by vesper8** [AyrA/ScreenFix#1]
would love to use this but am on Mac... thanks!

**Comment by AyrA** [comment]
It's not possible to easily rewrite the utility because it uses the `Forms` namespace, which only works on Windows.

[I wrote this website real quick though](https://cable.ayra.ch/screenfix/) to make it work on any system that runs a web browser

**Comment by vesper8** [comment]
cool! thanks for sharing!

I was feeling motivated today so I put this together

https://gist.github.com/vesper8/9b515b1a6ac7c7cb44f3389f7c137634

You can see it in action here https://cbass.ca/burnfix (click anywhere for fullscreen)

Cheers!
